### ISSUE TITLE
Zowe child processes not terminated when ZOWESVR is cancelled when using Zowe 1.2.0 with Node.js v8.1.15 Open Beta

### ISSUE THREAD

**Issue by kathysychan** [zowe/zlux-server-framework#98] opened 2019-05-09 14:14 UTC
**Describe the bug**
When I run Zowe 1.2.0 with Node.js v8.1.15 Open Beta, if I cancel the ZOWESVR started task, some Zowe child process is left hanging around. When I tried to start ZOWESVR again, it will not come up properly (probably because the some ports are not available). I only start to notice this problem in Zowe 1.2.0. The same Node.js v8 beta driver works well in Zowe 1.1.0. This makes us believe that the problem might be related to a recent change to use nodeCluster rather than nodeServer. 

Node.js v8.15 Open Beta can be downloaded from:

https://developer.ibm.com/mainframe/2019/04/24/sdk-for-node-js-z-os-open-beta/

There's documentation is available on that site for how to install that.

**To Reproduce**
1. Start Zowesvr by issuing "/s zowesvr". Notice that there are 18 child processes started.
2. After Zowesvr fully comes up (in about 5 minutes), type "/c zowesvr" to stop the zowe server. 
3. After a couple minutes, go to "da" and "ps" and notice that there are still 9 zowe child processes left. 
4. If you issue "/s zowesvr" again, the MVD would not come up.

**Expected behavior**
Zowe server can be bring up and down and still works properly

**Comment by kathysychan** [comment] 2019-05-09 14:24
Please contact @kiril-ibm if you need more information on how to reproduce the problem.

@John-A-Davies FYI.

**Comment by John-A-Davies** [comment] 2019-05-09 16:14
I started just the `zlux-app-server` with `nodeCluster.sh` with node v8.15.1 and cancelled the master STC.  These tasks remained after the CANCEL:
![image](https://user-images.githubusercontent.com/36740892/57468580-a1f1cb80-727c-11e9-85c8-c32b516a5cac.png)

and now the PS display shows
![image](https://user-images.githubusercontent.com/36740892/57468672-d796b480-727c-11e9-8379-444ff7820d52.png)

Note that `node --harmony zluxCluster.js` is using 50% CPU.

**Comment by John-A-Davies** [comment] 2019-05-10 08:07
I'm in favour of re-classifying this problem as a Node.js v8.15 problem.

**Comment by IgorTodorovskiIBM** [comment] 2019-05-13 04:10
Hi John/Kathy,

We have a fix in Node.js v8.16, which I have installed for you on the test system.   My tests show that performing "/C ZOWESVR" now kills the master Zowe process, including all children.  I have modified run-zowe.sh to reflect the change in the Node.js version.  

Can you please validate the behaviour?

Also, my initial suspicion that this issue was caused by orphaned processes seems to not be the case as Node.js v6 also has orphaned processes.  After examining /opt/zowe/zowe-1.2.0/zlux-app-server/node_modules/zlux-server-framework/lib/process.js, I believe zLux manages these processes and destroys them (via the call to endChildren) when a server shutdown is triggered.

**Comment by kiril-ibm** [comment] 2019-05-13 12:32
@IgorTodorovskiIBM Could you attach to the git issue change required in run-zowe.sh ?

**Comment by IgorTodorovskiIBM** [comment] 2019-05-13 12:40
@kiril-ibm , the change is to use the Node.js v8.16.0 driver in run-zowe.sh.   The driver is installed on host VM30051.

I have replaced the NODE_HOME and STEPLIB envars as such:
```
export NODE_HOME=/opt/nodejs/node-v8.16.0-os390-s390x
export STEPLIB=IBMUSER.NODEV8.NJSV8R0.BETA.CRT.SCEERUN2
```

Since we have yet to release the v8.16.0 driver externally, I can send it to you privately for validation.

**Comment by kiril-ibm** [comment] 2019-05-13 12:42
@IgorTodorovskiIBM thank you

**Comment by John-A-Davies** [comment] 2019-05-13 13:49
I cancelled ZOWESVR on vm30051 using node v8.16.0 and all STCs went down within a few seconds.

**Comment by kiril-ibm** [comment] 2019-05-13 16:06
I have these vars added to our CI/CD pipeline. I confirm that all child processes get cancelled. @IgorTodorovskiIBM when v8.16 will be GA ?

**Comment by IgorTodorovskiIBM** [comment] 2019-05-13 16:13
June 14th is the GA date.  We may refresh the Node.js v8 Open Beta sooner however.

**Comment by 1000TurquoisePogs** [comment] 2019-09-23 02:50
Closing this due to fix becoming available.

**Closed by 1000TurquoisePogs** 2019-09-23 02:50 UTC
